version: '3.8'

services:
  stockflow_db:
    image: mysql:8.0
    container_name: stockflow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_secure
      MYSQL_DATABASE: stockflow_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  stockflow_backend:
    build: ./backend
    container_name: stockflow_backend
    restart: always
    environment:
      - DB_HOST=stockflow_db
      - DB_USER=root
      - DB_PASSWORD=root_password_secure
      - DB_NAME=stockflow_db
    ports:
      - "8000:8000"
    depends_on:
      - stockflow_db

  stockflow_frontend:
    build: ./frontend
    container_name: stockflow_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - stockflow_backend

volumes:
  db_data:
  