import { createContext, useContext, useState } from 'react'

const translations = {
  fr: {
    // Sidebar
    dashboard: 'Dashboard',
    products: 'Produits',
    movements: 'Mouvements',
    history: 'Historique',
    invite: 'Inviter un utilisateur',
    administration: 'Administration',
    logout: 'Déconnexion',

    // Dashboard
    dashboardTitle: 'Dashboard',
    dashboardSub: "Bonjour, voici l'état de votre stock",
    totalReferences: 'Produits Référencés',
    totalStock: 'Unités en stock',
    alertCount: 'En alerte seuil',
    outOfStock: 'Rupture de stock',
    recentMovements: 'Mouvements récents',
    stockLevels: 'Niveaux par SKU',
    stockHealth: 'État de santé',
    alertProducts: 'Produits en alerte',
    seeAll: 'Voir tout →',
    noAlert: "Aucun produit sous le seuil d'alerte.",
    loading: 'Calcul des données analytiques...',
    sku: 'SKU',
    name: 'NOM',
    quantity: 'QUANTITÉ',
    threshold: 'SEUIL',
    status: 'STATUT',
    alert: 'ALERTE',
    inAlert: 'En Alerte',
    stockOk: 'Stock OK',

    // Products
    productsTitle: "Inventaire des produits",
    referencesFound: 'référence(s) trouvée(s)',
    newProduct: '+ Nouveau produit',
    cancel: '✕ Annuler',
    addProduct: 'Ajouter un produit',
    skuCode: 'Code SKU',
    productName: 'Nom du produit',
    initialStock: 'Quantité initiale',
    alertThreshold: "Seuil d'alerte",
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    catalog: 'Catalogue',
    search: 'Rechercher...',
    loadingProducts: 'Chargement...',
    noProducts: 'Aucun produit trouvé.',
    currentStock: 'Quantité',
    actions: 'Actions',
    delete: 'Supprimer',
    outOfStockBadge: 'Rupture',
    lowStock: 'Alerte',
    healthy: 'OK',
    productCreated: 'Produit créé avec succès',
    productDeleted: 'Produit supprimé avec succès',
    confirmDelete: 'Voulez-vous vraiment supprimer ce produit et son historique ?',

    // Movements
    movementsTitle: 'Mouvements de stock',
    movementsSub: 'Enregistrez une entrée ou sortie de stock',
    newMovement: 'Nouveau mouvement',
    selectProduct: '-- Sélectionner un produit --',
    quantityLabel: 'Quantité (+ entrée / − sortie)',
    quantityPlaceholder: 'Ex: -3 ou +10',
    reason: 'Motif',
    reasonPlaceholder: 'Vente client, réapprovisionnement…',
    recordMovement: 'Enregistrer le mouvement',
    recording: 'Enregistrement…',
    productPreview: 'Aperçu produit',
    selectProductPreview: 'Sélectionnez un produit pour voir son état',
    currentStockLabel: 'Stock actuel',
    afterMovement: 'Stock après mouvement',
    rupture: 'Rupture',
    alertSeuil: 'Alerte seuil',
    stockOkBadge: 'Stock OK',

    // History
    historyTitle: 'Historique des mouvements',
    historySub: 'Traçabilité complète des opérations de stock',
    entries: 'entrée(s)',
    searchHistory: 'Rechercher un produit, utilisateur, motif…',
    historyLoading: "Chargement de l'historique…",
    noHistory: 'Aucun mouvement enregistré pour le moment.',
    date: 'Date',
    product: 'Produit',
    user: 'Utilisateur',
    historyQuantity: 'Quantité',
    historyReason: 'Motif',

    // Login
    loginTitle: 'Connexion',
    loginSub: 'Accédez à votre espace de gestion de stock',
    email: 'Email',
    password: 'Mot de passe',
    loginBtn: 'Se connecter',
    loginLoading: 'Connexion…',
    loginBlocked: '🔒 Compte bloqué',
    noAccount: 'Pas encore de compte ?',
    createAccount: 'Créer un compte',
    incorrectCredentials: 'Identifiants incorrects',
    attemptsLeft: 'tentative(s) restante(s) avant blocage.',
    blocked: 'Trop de tentatives. Compte bloqué pendant 15 minutes.',

    // Register
    registerTitle: 'Créer une entreprise',
    registerSub: 'Inscrivez votre organisation pour commencer',
    companyName: "Nom de l'entreprise",
    companyPlaceholder: 'Ma Super Boîte',
    adminName: 'Votre nom (Admin)',
    adminNamePlaceholder: 'Jean Dupont',
    professionalEmail: 'Email professionnel',
    professionalEmailPlaceholder: 'jean@masuperboite.com',
    createCompany: "Créer l'espace entreprise",
    creating: 'Création…',
    alreadyAccount: 'Déjà un compte ?',
    signIn: 'Se connecter',

    // InviteUser
    inviteTitle: 'Inviter un utilisateur',
    inviteSub: 'Ajoutez un membre à votre organisation',
    fullName: 'Nom complet',
    fullNamePlaceholder: 'Jean Dupont',
    tempPassword: 'Mot de passe temporaire',
    role: 'Rôle',
    roleUser: 'Utilisateur',
    roleAdmin: 'Administrateur',
    createUser: 'Créer le compte',
    adminOnly: 'Accès réservé aux administrateurs.',
  },

  en: {
    dashboard: 'Dashboard',
    products: 'Products',
    movements: 'Movements',
    history: 'History',
    invite: 'Invite user',
    administration: 'Administration',
    logout: 'Logout',

    dashboardTitle: 'Dashboard',
    dashboardSub: 'Hello, here is your stock status',
    totalReferences: 'Referenced Products',
    totalStock: 'Units in stock',
    alertCount: 'Below threshold',
    outOfStock: 'Out of stock',
    recentMovements: 'Recent movements',
    stockLevels: 'Stock levels by SKU',
    stockHealth: 'Stock health',
    alertProducts: 'Alert products',
    seeAll: 'See all →',
    noAlert: 'No products below alert threshold.',
    loading: 'Computing analytics...',
    sku: 'SKU',
    name: 'NAME',
    quantity: 'QUANTITY',
    threshold: 'THRESHOLD',
    status: 'STATUS',
    alert: 'ALERT',
    inAlert: 'In Alert',
    stockOk: 'Stock OK',

    productsTitle: 'Products Inventory',
    referencesFound: 'reference(s) found',
    newProduct: '+ New product',
    cancel: '✕ Cancel',
    addProduct: 'Add product',
    skuCode: 'SKU Code',
    productName: 'Product name',
    initialStock: 'Initial stock',
    alertThreshold: 'Alert threshold',
    save: 'Save',
    saving: 'Saving...',
    catalog: 'Catalog',
    search: 'Search...',
    loadingProducts: 'Loading...',
    noProducts: 'No products found.',
    currentStock: 'Quantity',
    actions: 'Actions',
    delete: 'Delete',
    outOfStockBadge: 'Out of stock',
    lowStock: 'Low stock',
    healthy: 'Healthy',
    productCreated: 'Product created successfully',
    productDeleted: 'Product deleted successfully',
    confirmDelete: 'Are you sure you want to permanently delete this product and its history?',

    movementsTitle: 'Stock movements',
    movementsSub: 'Record a stock entry or exit',
    newMovement: 'New movement',
    selectProduct: '-- Select a product --',
    quantityLabel: 'Quantity (+ entry / − exit)',
    quantityPlaceholder: 'e.g: -3 or +10',
    reason: 'Reason',
    reasonPlaceholder: 'Customer sale, restocking…',
    recordMovement: 'Record movement',
    recording: 'Recording…',
    productPreview: 'Product preview',
    selectProductPreview: 'Select a product to see its status',
    currentStockLabel: 'Current stock',
    afterMovement: 'Stock after movement',
    rupture: 'Out of stock',
    alertSeuil: 'Low stock',
    stockOkBadge: 'Stock OK',

    historyTitle: 'Movement history',
    historySub: 'Complete traceability of stock operations',
    entries: 'entry(ies)',
    searchHistory: 'Search by product, user, reason…',
    historyLoading: 'Loading history…',
    noHistory: 'No movements recorded yet.',
    date: 'Date',
    product: 'Product',
    user: 'User',
    historyQuantity: 'Quantity',
    historyReason: 'Reason',

    loginTitle: 'Login',
    loginSub: 'Access your inventory management space',
    email: 'Email',
    password: 'Password',
    loginBtn: 'Sign in',
    loginLoading: 'Signing in…',
    loginBlocked: '🔒 Account locked',
    noAccount: 'No account yet?',
    createAccount: 'Create an account',
    incorrectCredentials: 'Incorrect credentials',
    attemptsLeft: 'attempt(s) left before lockout.',
    blocked: 'Too many attempts. Account locked for 15 minutes.',

    registerTitle: 'Create a company',
    registerSub: 'Register your organization to get started',
    companyName: 'Company name',
    companyPlaceholder: 'My Company',
    adminName: 'Your name (Admin)',
    adminNamePlaceholder: 'John Doe',
    professionalEmail: 'Professional email',
    professionalEmailPlaceholder: 'john@mycompany.com',
    createCompany: 'Create company space',
    creating: 'Creating…',
    alreadyAccount: 'Already have an account?',
    signIn: 'Sign in',

    inviteTitle: 'Invite a user',
    inviteSub: 'Add a member to your organization',
    fullName: 'Full name',
    fullNamePlaceholder: 'John Doe',
    tempPassword: 'Temporary password',
    role: 'Role',
    roleUser: 'User',
    roleAdmin: 'Administrator',
    createUser: 'Create account',
    adminOnly: 'Access restricted to administrators.',
  },

  es: {
    dashboard: 'Panel',
    products: 'Productos',
    movements: 'Movimientos',
    history: 'Historial',
    invite: 'Invitar usuario',
    administration: 'Administración',
    logout: 'Cerrar sesión',

    dashboardTitle: 'Panel de control',
    dashboardSub: 'Hola, aquí está el estado de tu stock',
    totalReferences: 'Productos referenciados',
    totalStock: 'Unidades en stock',
    alertCount: 'Bajo umbral',
    outOfStock: 'Sin stock',
    recentMovements: 'Movimientos recientes',
    stockLevels: 'Niveles por SKU',
    stockHealth: 'Salud del stock',
    alertProducts: 'Productos en alerta',
    seeAll: 'Ver todo →',
    noAlert: 'Ningún producto bajo el umbral de alerta.',
    loading: 'Calculando datos analíticos...',
    sku: 'SKU',
    name: 'NOMBRE',
    quantity: 'CANTIDAD',
    threshold: 'UMBRAL',
    status: 'ESTADO',
    alert: 'ALERTA',
    inAlert: 'En alerta',
    stockOk: 'Stock OK',

    productsTitle: 'Inventario de productos',
    referencesFound: 'referencia(s) encontrada(s)',
    newProduct: '+ Nuevo producto',
    cancel: '✕ Cancelar',
    addProduct: 'Agregar producto',
    skuCode: 'Código SKU',
    productName: 'Nombre del producto',
    initialStock: 'Stock inicial',
    alertThreshold: 'Umbral de alerta',
    save: 'Guardar',
    saving: 'Guardando...',
    catalog: 'Catálogo',
    search: 'Buscar...',
    loadingProducts: 'Cargando...',
    noProducts: 'No se encontraron productos.',
    currentStock: 'Cantidad',
    actions: 'Acciones',
    delete: 'Eliminar',
    outOfStockBadge: 'Sin stock',
    lowStock: 'Stock bajo',
    healthy: 'OK',
    productCreated: 'Producto creado exitosamente',
    productDeleted: 'Producto eliminado exitosamente',
    confirmDelete: '¿Estás seguro de que quieres eliminar este producto y su historial?',

    movementsTitle: 'Movimientos de stock',
    movementsSub: 'Registra una entrada o salida de stock',
    newMovement: 'Nuevo movimiento',
    selectProduct: '-- Seleccionar un producto --',
    quantityLabel: 'Cantidad (+ entrada / − salida)',
    quantityPlaceholder: 'Ej: -3 o +10',
    reason: 'Motivo',
    reasonPlaceholder: 'Venta a cliente, reabastecimiento…',
    recordMovement: 'Registrar movimiento',
    recording: 'Registrando…',
    productPreview: 'Vista previa del producto',
    selectProductPreview: 'Selecciona un producto para ver su estado',
    currentStockLabel: 'Stock actual',
    afterMovement: 'Stock después del movimiento',
    rupture: 'Sin stock',
    alertSeuil: 'Stock bajo',
    stockOkBadge: 'Stock OK',

    historyTitle: 'Historial de movimientos',
    historySub: 'Trazabilidad completa de las operaciones de stock',
    entries: 'entrada(s)',
    searchHistory: 'Buscar por producto, usuario, motivo…',
    historyLoading: 'Cargando historial…',
    noHistory: 'No hay movimientos registrados aún.',
    date: 'Fecha',
    product: 'Producto',
    user: 'Usuario',
    historyQuantity: 'Cantidad',
    historyReason: 'Motivo',

    loginTitle: 'Iniciar sesión',
    loginSub: 'Accede a tu espacio de gestión de stock',
    email: 'Correo electrónico',
    password: 'Contraseña',
    loginBtn: 'Iniciar sesión',
    loginLoading: 'Iniciando sesión…',
    loginBlocked: '🔒 Cuenta bloqueada',
    noAccount: '¿No tienes cuenta?',
    createAccount: 'Crear una cuenta',
    incorrectCredentials: 'Credenciales incorrectas',
    attemptsLeft: 'intento(s) restante(s) antes del bloqueo.',
    blocked: 'Demasiados intentos. Cuenta bloqueada durante 15 minutos.',

    registerTitle: 'Crear una empresa',
    registerSub: 'Registra tu organización para comenzar',
    companyName: 'Nombre de la empresa',
    companyPlaceholder: 'Mi Empresa',
    adminName: 'Tu nombre (Admin)',
    adminNamePlaceholder: 'Juan García',
    professionalEmail: 'Correo profesional',
    professionalEmailPlaceholder: 'juan@miempresa.com',
    createCompany: 'Crear espacio empresarial',
    creating: 'Creando…',
    alreadyAccount: '¿Ya tienes cuenta?',
    signIn: 'Iniciar sesión',

    inviteTitle: 'Invitar un usuario',
    inviteSub: 'Agrega un miembro a tu organización',
    fullName: 'Nombre completo',
    fullNamePlaceholder: 'Juan García',
    tempPassword: 'Contraseña temporal',
    role: 'Rol',
    roleUser: 'Usuario',
    roleAdmin: 'Administrador',
    createUser: 'Crear cuenta',
    adminOnly: 'Acceso restringido a administradores.',
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sf_lang') || 'fr')

  function changeLang(newLang) {
    setLang(newLang)
    localStorage.setItem('sf_lang', newLang)
  }

  const t = translations[lang]

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)